Repository SeungYoonPark/And3-4project, pull requests merged in 2023-09, with the labels that each got.

#1 [DESIGN] : 🎨 MyPageFragment
  app/src/main/java/com/example/and3_4project/MyPageFragment.kt
  app/src/main/res/drawable/cat.jpg
  app/src/main/res/drawable/icon_add_person.png
  app/src/main/res/drawable/icon_add_person2.png
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: UI

#2 [FEAT] : ⚙️ ContactListFragment
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/example/and3_4project/Adapter.kt
  app/src/main/java/com/example/and3_4project/ContactList.kt
  app/src/main/java/com/example/and3_4project/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_recyclerview.xml
Labels: Feature

#3 Feature add contact dialog fragment
  app/build.gradle.kts
  app/src/main/java/com/example/and3_4project/MainActivity.kt
  app/src/main/res/drawable/add.png
  app/src/main/res/drawable/user.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: Feature

#5 Feature view pager2
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/example/and3_4project/ContactList.kt
  app/src/main/java/com/example/and3_4project/ContactListFragment.kt
  app/src/main/java/com/example/and3_4project/FragmentpageAdapter.kt
  app/src/main/java/com/example/and3_4project/MainActivity.kt
  app/src/main/java/com/example/and3_4project/MyPageFragment.kt
  app/src/main/res/drawable/cat.jpg
  app/src/main/res/drawable/icon_add_person.png
  app/src/main/res/drawable/icon_add_person2.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_fragmentpage_adapter.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_recyclerview.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: Feature

#14 [DESIGN] : 🎨 MyPageFragment
  app/src/main/res/drawable/buttonshape.xml
  app/src/main/res/drawable/icon_back.png
  app/src/main/res/drawable/icon_menu.png
  app/src/main/res/drawable/icon_message.png
  app/src/main/res/drawable/icon_notification.png
  app/src/main/res/drawable/icon_phone.png
  app/src/main/res/drawable/message.png
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/colors.xml
Labels: UI

#16 UI detail
  app/src/main/java/com/example/and3_4project/ContactDetailFragment.kt
  app/src/main/java/com/example/and3_4project/DetailActivty.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/menu/toolbar_menu.xml
  app/src/main/res/values/styles.xml
Labels: UI

#18 [FEAT] : ⚙️ 싱글톤 작업
  app/build.gradle.kts
  app/src/main/java/com/example/and3_4project/ContactDetailActivity.kt
  app/src/main/java/com/example/and3_4project/ContactDetailFragment.kt
  app/src/main/java/com/example/and3_4project/ContactList.kt
  app/src/main/java/com/example/and3_4project/ContactListFragment.kt
  app/src/main/java/com/example/and3_4project/InfoSingleton.kt
  app/src/main/java/com/example/and3_4project/MainActivity.kt
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_recyclerview.xml
Labels: Feature

#19 [DESIGN] : 🎨 전체적인 통일감 주기
  app/src/main/java/com/example/and3_4project/ContactListFragment.kt
  app/src/main/java/com/example/and3_4project/MainActivity.kt
  app/src/main/res/drawable/icon_add_photo.png
  app/src/main/res/drawable/message_button.xml
  app/src/main/res/drawable/notification_button.xml
  app/src/main/res/drawable/phone_button.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_recyclerview.xml
  app/src/main/res/values/colors.xml
Labels: Design

#24 [DESIGN] : 🎨 전체적인 통일감 주기
  .idea/render.experimental.xml
  app/src/main/java/com/example/and3_4project/Contact/ContactDetailActivity.kt
  app/src/main/java/com/example/and3_4project/Contact/RecyclerViewAdapter.kt
  app/src/main/java/com/example/and3_4project/Main/InfoSingleton.kt
  app/src/main/java/com/example/and3_4project/Main/MainActivity.kt
  app/src/main/res/color/tab_color_selector.xml
  app/src/main/res/drawable/custom_toggle_bg.xml
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/heart1.png
  app/src/main/res/drawable/heart_fill.png
  app/src/main/res/drawable/profile.xml
  app/src/main/res/drawable/profile_white.png
  app/src/main/res/drawable/setting.xml
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_recyclerview.xml
  app/src/main/res/menu/toolbar_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: UI

#27 [FEAT] : ⚙️ 전화걸기 연결완료
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/and3_4project/Contact/ContactDetailActivity.kt
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/heart_fill.png
  app/src/main/res/drawable/icon_back.png
  app/src/main/res/drawable/icon_back_2.xml
  app/src/main/res/drawable/icon_menu.png
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/menu/toolbar_menu.xml
Labels: Feature

#29 [FEAT] : ⚙️ contactListFragment 메뉴 누르면 변경
  app/src/main/java/com/example/and3_4project/Contact/ContactListFragment.kt
  app/src/main/java/com/example/and3_4project/Contact/RecyclerViewAdapter.kt
  app/src/main/res/drawable/grid.png
  app/src/main/res/drawable/list.png
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/item_grid_recyclerview.xml
  app/src/main/res/menu/contact_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#30 [FEAT] : ⚙️ 전화걸기 연결완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/and3_4project/Contact/ContactDetailActivity.kt
Labels: Feature

#32 Fix toolbar
  app/src/main/java/com/example/and3_4project/Main/MainActivity.kt
  app/src/main/res/drawable/icon_menu.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/menu/contact_toolbar.xml
Labels: Fix or ETX

#33 [DESIGN] : 🎨 icon추가
  app/src/main/res/drawable/icon_menu_line.xml
Labels: Design

#34 [FEAT] : ⚙️ contactListFragment 그리드뷰 전환
  app/src/main/java/com/example/and3_4project/Contact/ContactListFragment.kt
Labels: Feature

#40 [DESIGN] : 🎨 다이얼로그
  app/src/main/java/com/example/and3_4project/Main/InfoSingleton.kt
  app/src/main/res/color/text_color.xml
  app/src/main/res/drawable/bbang.png
  app/src/main/res/drawable/button_off.xml
  app/src/main/res/drawable/button_on.xml
  app/src/main/res/drawable/cat10.jpg
  app/src/main/res/drawable/cat14.jpeg
  app/src/main/res/drawable/cat5.png
  app/src/main/res/drawable/custom_toggle_bg.xml
  app/src/main/res/drawable/dog1.jpeg
  app/src/main/res/drawable/icon_contact.xml
  app/src/main/res/drawable/oksun.png
  app/src/main/res/drawable/poketmon.jpeg
  app/src/main/res/drawable/poketmon2.png
  app/src/main/res/drawable/profile_set.png
  app/src/main/res/drawable/profile_set1.jpg
  app/src/main/res/drawable/profile_set2.jpg
  app/src/main/res/drawable/profile_set3.jpg
  app/src/main/res/drawable/profile_set4.jpg
  app/src/main/res/drawable/toggle_selector.xml
  app/src/main/res/layout/activity_contact_detail.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: UI

#42 [FEAT] : ⚙️ customItemTouchHelper(swipe)
  app/src/main/java/com/example/and3_4project/Contact/ContactListFragment.kt
  app/src/main/java/com/example/and3_4project/Contact/GridRecyclerViewAdapter.kt
  app/src/main/java/com/example/and3_4project/Contact/RecyclerViewAdapter.kt
  app/src/main/java/com/example/and3_4project/CustomItemTouchHelper.kt
Labels: Feature

#43 [DESIGN] : 🎨 스와이프시 오른쪽 컬러
  app/src/main/java/com/example/and3_4project/CustomItemTouchHelper.kt
Labels: Design

#44 [BUGFIX] : 🐛 각 리사이클러뷰의 phoneNumber에 전화걸기
  app/src/main/java/com/example/and3_4project/Contact/ContactListFragment.kt
Labels: Fix or ETX

#47 [BUGFIX] : 🐛 다이얼로그 프로필사진 추가
  app/src/main/java/com/example/and3_4project/Contact/ContactDetailActivity.kt
  app/src/main/java/com/example/and3_4project/Contact/ContactListFragment.kt
  app/src/main/java/com/example/and3_4project/Contact/RecyclerViewAdapter.kt
  app/src/main/java/com/example/and3_4project/CustomItemTouchHelper.kt
  app/src/main/java/com/example/and3_4project/Main/MainActivity.kt
  app/src/main/java/com/example/and3_4project/Main/MyPageFragment.kt
Labels: bug
